# Generated by Django 5.2.8 on 2025-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("description", models.TextField()),
                ("schedule_json", models.JSONField()),
                ("coach_note", models.TextField(blank=True)),
                ("reflection_text", models.TextField(blank=True)),
                (
                    "energy_morning",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "energy_afternoon",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "energy_evening",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SavedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("default_duration_minutes", models.IntegerField(default=30)),
                ("default_importance", models.IntegerField(default=2)),
                ("category", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("preferred_sleep_time", models.TimeField(blank=True, null=True)),
                ("preferred_wake_time", models.TimeField(blank=True, null=True)),
                (
                    "max_study_hours",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "break_frequency_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "preferred_focus_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "study_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("long_blocks", "Long Focus Blocks"),
                            ("pomodoro", "Pomodoro (25/5)"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "stress_sensitivity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("plays_sport", models.BooleanField(default=False)),
            ],
        ),
    ]
